name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: export with Godot Engine and release on GitHub
        uses: firebelley/godot-export@v4.7.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_x11.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5.1/Godot_v3.5.1-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./dist
          use_godot_4: true
          archive_output: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./dist
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: ${{ secrets.ITCH_GAME_ID }}
          buildChannel: win
