name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_game:
    name: Build Game
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: export with Godot Engine and release on GitHub
        uses: firebelley/godot-export@v4.7.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.0-stable/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
